
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-happycows
owner: ucsb-cs156
repo_name: proj-happycows
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-hide-swagger","number":221,"title":"pc - refactor Developer page and hide swagger link on prod (except on Developer Page) by default","url":"https://github.com/ucsb-cs156/proj-happycows/pull/221"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-hideCommons","number":217,"title":"Hidden Commons: Hide hidden commons on PlayPage and HomePage","url":"https://github.com/ucsb-cs156/proj-happycows/pull/217"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-hidden-frontend-admin-updates","number":213,"title":"Hidden Commons: Make \"hidden\" field settable and visible in frontend.","url":"https://github.com/ucsb-cs156/proj-happycows/pull/213"}]
