
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-happycows
owner: ucsb-cs156
repo_name: proj-happycows
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-hidden-frontend-admin-updates","number":213,"title":"Pc hidden frontend admin updates","url":"https://github.com/ucsb-cs156/proj-happycows/pull/213"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-hide-backend-update","number":212,"title":"Pc hide backend update","url":"https://github.com/ucsb-cs156/proj-happycows/pull/212"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-15","number":199,"title":"F25 15","url":"https://github.com/ucsb-cs156/proj-happycows/pull/199"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-14","number":198,"title":"f25-14","url":"https://github.com/ucsb-cs156/proj-happycows/pull/198"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-13","number":197,"title":"f25-13","url":"https://github.com/ucsb-cs156/proj-happycows/pull/197"}]
